// src/components/HeroCard.tsx
"use client";

import { Hero } from "@/types/hero";
import { useHeroes } from "@/context/HeroContext";

interface HeroCardProps {
  hero: Hero;
}

export default function HeroCard({ hero }: HeroCardProps) {
  const { getHeroSelected, toggleHero } = useHeroes();
  const selected = getHeroSelected(hero.key);

  return (
    <div
      className={`hero-card ${selected ? "selected" : ""}`}
      onClick={() => toggleHero(hero.key)}
    >
      <img
        className="hero-card-image"
        alt={`${hero.name} icon`}
        src={`/assets/imgs/heroes/icons/${hero.key}.png`}
      />
      <div className="hero-card-name">{hero.name}</div>
    </div>
  );
}

// src/app/components/content/hero-card/hero-card.component.ts
import { Component, Input, OnInit } from '@angular/core';
import { Hero } from '../../../models/hero';
import { HeroesService } from '../../../services/heroes.service';


@Component({
  selector: 'app-hero-card',
  templateUrl: './hero-card.component.html',
  styleUrls: ['./hero-card.component.css']
})
export class HeroCardComponent implements OnInit {
  constructor(
    private heroesService: HeroesService
  ) { }

  @Input() hero: Hero;

  ngOnInit() {
  }

  toggle(hero: Hero) {
    this.heroesService.toggleHero(hero);
  }

}


<div [class.selected]="hero.selected === true" class="card" (click)="toggle(hero)">
    <img src="../../../../assets/imgs/heroes/icons/{{hero.key}}.png">
    <button [class.selected]="hero.selected === true">{{hero.name}}</button>
</div>
