// overwatch-hero-picker-nextjs/src/components/PickerContent.tsx
'use client';

import { useState, useEffect } from 'react';
import { Hero, HeroRole } from '@/types/heroes';
import { useHeroes } from '@/hooks/useHeroes';
import HeroCard from './HeroCard';
import Image from 'next/image';
import Link from 'next/link';

export default function PickerContent() {
  const {
    toggleHero,
    selectByRole,
    unselectByRole,
    selectJustRole,
    getHeroesByRole,
    getSelectedHeroes,
    getRandomHero,
    getRandomHeroPerks,
  } = useHeroes();

  const [selectedHero, setSelectedHero] = useState<Hero | null>(null);
  const [perks, setPerks] = useState<[string, string]>(['', '']);
  const [heroCount, setHeroCount] = useState(0);
  const [showPortrait, setShowPortrait] = useState(true);
  const [showPerks, setShowPerks] = useState(true);

  // Load preferences from localStorage
  useEffect(() => {
    if (typeof window !== 'undefined') {
      const savedShowPortrait = localStorage.getItem('showPortrait');
      const savedShowPerks = localStorage.getItem('showPerks');

      if (savedShowPortrait !== null) {
        setShowPortrait(savedShowPortrait === 'true');
      }

      if (savedShowPerks !== null) {
        setShowPerks(savedShowPerks === 'true');
      }

      // Set initial random hero
      const randomHero = getRandomHero();
      setSelectedHero(randomHero);
      if (randomHero) {
        setPerks(getRandomHeroPerks(randomHero.key));
      }
    }
  }, [getRandomHero, getRandomHeroPerks]);

  // Save preferences to localStorage
  useEffect(() => {
    if (typeof window !== 'undefined') {
      localStorage.setItem('showPortrait', showPortrait.toString());
    }
  }, [showPortrait]);

  useEffect(() => {
    if (typeof window !== 'undefined') {
      localStorage.setItem('showPerks', showPerks.toString());
    }
  }, [showPerks]);

  const handleRandomHero = () => {
    const newHero = getRandomHero();
    setSelectedHero(newHero);
    setHeroCount(prev => prev + 1);
    if (newHero) {
      setPerks(getRandomHeroPerks(newHero.key));
    }
  };

  const handleRandomPerks = () => {
    if (selectedHero) {
      setPerks(getRandomHeroPerks(selectedHero.key));
    }
  };

  const selectedHeroes = getSelectedHeroes();
  const numberOfSelectedHeroes = selectedHeroes.length;

  const roleButtons = (
    role: HeroRole,
    roleDisplayName: string,
    roleIcon: string
  ) => (
    <div className="flex items-center mb-4">
      <Image
        src={roleIcon}
        alt={`${roleDisplayName} role icon`}
        width={32}
        height={32}
        className="max-h-8 mr-2"
        unoptimized
      />
      <h2 className="text-2xl mr-4">{roleDisplayName}</h2>
      <button
        className="bg-green-600 hover:bg-green-700 text-white px-3 py-1 mx-1 text-lg transform -skew-x-3 hover:cursor-pointer active:translate-x-px active:translate-y-px"
        onClick={() => selectByRole(role)}
      >
        Select All
      </button>
      <button
        className="bg-orange-600 hover:bg-orange-700 text-white px-3 py-1 mx-1 text-lg transform -skew-x-3 hover:cursor-pointer active:translate-x-px active:translate-y-px"
        onClick={() => unselectByRole(role)}
      >
        Unselect All
      </button>
      <button
        className="bg-gray-600 hover:bg-gray-700 text-white px-3 py-1 mx-1 text-lg transform -skew-x-3 hover:cursor-pointer active:translate-x-px active:translate-y-px"
        onClick={() => selectJustRole(role)}
      >
        Just this role
      </button>
    </div>
  );

  return (
    <div className="flex flex-col lg:flex-row w-full min-h-screen p-0 m-0 bg-primary text-white unselectable">
      {/* Left Content */}
      <div className="flex flex-col lg:w-1/4 px-6 py-4">
        <h1 className="text-3xl mb-4 underline">You should play</h1>

        <div className="mb-4">
          <label className="inline-flex items-center mr-4">
            <input
              type="checkbox"
              checked={showPortrait}
              onChange={e => setShowPortrait(e.target.checked)}
              className="mr-2"
            />
            <span>Show hero portrait</span>
          </label>

          <label className="inline-flex items-center">
            <input
              type="checkbox"
              checked={showPerks}
              onChange={e => setShowPerks(e.target.checked)}
              className="mr-2"
            />
            <span>Randomize perks</span>
          </label>
        </div>

        {showPortrait && selectedHero && (
          <Image
            src={`/assets/imgs/heroes/portraits/${selectedHero.key}.png`}
            alt={`${selectedHero.name} portrait`}
            width={200}
            height={200}
            className="max-w-3/4 mx-auto mb-4"
            unoptimized
          />
        )}

        {selectedHero && (
          <div
            key={`hero-name-${selectedHero.name}-${heroCount}`}
            className="mb-4"
          >
            <h2 className="text-2xl font-bold">
              {selectedHero.name}
              {showPerks && (
                <div className="text-base leading-tight mt-2">
                  <span className="text-sm">
                    {perks[0]} | {perks[1]}
                  </span>
                  <br />
                  <span
                    className="text-base text-orange-600 underline cursor-pointer hover:text-orange-500"
                    onClick={handleRandomPerks}
                  >
                    New perks
                  </span>
                </div>
              )}
            </h2>
          </div>
        )}

        <button
          className="bg-orange-600 hover:bg-orange-700 text-white font-bold py-2 px-4 rounded text-xl"
          onClick={handleRandomHero}
        >
          Get Random Hero
        </button>
      </div>

      {/* Right Content */}
      <div className="lg:w-3/4 px-6 py-4 text-left lg:text-left text-center">
        <h1 className="text-3xl mb-4 underline">Filter Heroes</h1>

        <p className="text-base font-bold mb-2">
          Select the heroes you wish to play and click in the &quot;Get Random
          Hero&quot; button to get a random hero from the selected ones.
        </p>

        <p className="text-base font-bold mb-4">
          Playing as a group?{' '}
          <Link
            href="/squad"
            className="text-orange-500 underline hover:text-orange-600"
          >
            Get random heroes for your team
          </Link>
        </p>

        <div className="text-lg text-orange-500 font-bold mb-4">
          {numberOfSelectedHeroes === 0 && (
            <p>
              You have no heroes selected, so all heroes are being considered by
              default.
            </p>
          )}
          {numberOfSelectedHeroes === 1 && (
            <p>You have {numberOfSelectedHeroes} hero selected.</p>
          )}
          {numberOfSelectedHeroes > 1 && (
            <p>You have {numberOfSelectedHeroes} heroes selected.</p>
          )}
        </div>

        {/* Tank Heroes */}
        {roleButtons('TANK', 'Tank', '/assets/imgs/roles/tank.png')}
        <div className="flex flex-wrap justify-start mb-6">
          {getHeroesByRole('TANK').map(hero => (
            <HeroCard key={hero.key} hero={hero} onToggle={toggleHero} />
          ))}
        </div>

        {/* Damage Heroes */}
        {roleButtons('DAMAGE', 'Damage', '/assets/imgs/roles/damage.png')}
        <div className="flex flex-wrap justify-start mb-6">
          {getHeroesByRole('DAMAGE').map(hero => (
            <HeroCard key={hero.key} hero={hero} onToggle={toggleHero} />
          ))}
        </div>

        {/* Support Heroes */}
        {roleButtons('SUPPORT', 'Support', '/assets/imgs/roles/support.png')}
        <div className="flex flex-wrap justify-start mb-6">
          {getHeroesByRole('SUPPORT').map(hero => (
            <HeroCard key={hero.key} hero={hero} onToggle={toggleHero} />
          ))}
        </div>
      </div>
    </div>
  );
}

// src/pages/PickerContent.vue
<template>
  <div class="main-container col-12 h-100 m-0 p-0 unselectable">
    <div class="row col-12 m-0 p-0">
      <div class="left-content col-lg-3">
        <h1 class="left-title">You should play</h1>

        <div>
          <input
            id="checkbox-show-portrait"
            v-model="showPortrait"
            :value="true"
            type="checkbox"
            name="checkbox-show-portrait"
          />
          <label
            id="show-portrait-label"
            for="checkbox-show-portrait"
            class="show-portrait-label"
            >Show hero portrait
          </label>
        </div>

        <img
          v-if="showPortrait"
          key="hero-image"
          :src="'assets/imgs/heroes/portraits/' + selectedHero.key + '.png'"
          class="chosen-hero-image img-fluid"
        />

        <transition name="hero-name-transition" mode="out-in">
          <h2
            :key="`hero-name-${selectedHero.name}-${heroCount}`"
            class="chosen-hero-name"
          >
            {{ selectedHero.name }}
          </h2>
        </transition>

        <div
          type="button"
          class="random-hero-button"
          @click="randomHeroHandler"
        >
          Get Random Hero
        </div>
      </div>

      <div class="right-content col-lg-9">
        <h1 class="right-title">Filter Heroes</h1>

        <p class="filter-description">
          Select the heroes you wish to play and click in the "Get Random Hero"
          button to get a random hero from the selected ones.
        </p>

        <p class="filter-description">
          Playing as a group?
          <router-link to="/squad">Get random heroes for your team</router-link>
        </p>

        <div class="filter-description selected-heroes-info">
          <p
            v-if="numberOfSelectedHeroes === 0"
            class="filter-description selected-heroes-text"
          >
            You have no heroes selected, so all heroes are being considered by
            default.
          </p>
          <p
            v-else-if="numberOfSelectedHeroes === 1"
            class="filter-description selected-heroes-text"
          >
            You have {{ numberOfSelectedHeroes }} hero selected.
          </p>
          <p v-else class="filter-description selected-heroes-text">
            You have {{ numberOfSelectedHeroes }} heroes selected.
          </p>
        </div>

        <div class="filter-header">
          <img
            class="role-icon"
            alt="Tank role icon"
            src="assets/imgs/roles/tank.png"
          />
          <h2 class="role-header">Tank</h2>
          <button
            class="all-button select-all-button"
            @click="selectByRole('TANK')"
          >
            Select All
          </button>
          <button
            class="all-button unselect-all-button"
            @click="unselectByRole('TANK')"
          >
            Unselect All
          </button>
        </div>

        <div class="card-group">
          <HeroCard
            v-for="h in getHeroesByRole('TANK')"
            :key="h.key"
            :hero="h"
          />
        </div>

        <div class="filter-header">
          <img
            class="role-icon"
            alt="Damage role icon"
            src="assets/imgs/roles/damage.png"
          />
          <h2 class="role-header">Damage</h2>
          <button
            class="all-button select-all-button"
            @click="selectByRole('DAMAGE')"
          >
            Select All
          </button>
          <button
            class="all-button unselect-all-button"
            @click="unselectByRole('DAMAGE')"
          >
            Unselect All
          </button>
        </div>

        <div class="card-group">
          <HeroCard
            v-for="h in getHeroesByRole('DAMAGE')"
            :key="h.key"
            :hero="h"
          />
        </div>

        <div class="filter-header">
          <img
            class="role-icon"
            alt="Support role icon"
            src="assets/imgs/roles/support.png"
          />
          <h2 class="role-header">Support</h2>
          <button
            class="all-button select-all-button"
            @click="selectByRole('SUPPORT')"
          >
            Select All
          </button>
          <button
            class="all-button unselect-all-button"
            @click="unselectByRole('SUPPORT')"
          >
            Unselect All
          </button>
        </div>
        <div class="card-group">
          <HeroCard
            v-for="h in getHeroesByRole('SUPPORT')"
            :key="h.key"
            :hero="h"
          />
        </div>
      </div>
    </div>
  </div>
</template>

<script>
import {
  randomHero,
  getHeroesByRole,
  selectByRole,
  unselectByRole,
  saveSelectedHeroesToLS,
  getSelectedLSHeroes,
  getSelected,
} from "../services/heroes_service";
import HeroCard from "@/components/HeroCard";
import { sendEvent } from "../services/events";

export default {
  name: "PickerPageContent",
  components: {
    HeroCard,
  },
  data() {
    return {
      selectedHero: {
        name: "",
        role: "",
        selected: false,
        key: "",
      },
      heroCount: 0,
      showPortrait: true,
    };
  },
  computed: {
    selectedHeroes: function () {
      return getSelected().map((h) => h.name);
    },
    numberOfSelectedHeroes: function () {
      return this.selectedHeroes.length;
    },
  },
  watch: {
    showPortrait: function (newValue) {
      localStorage.setItem("showPortrait", newValue);
      sendEvent("Option", "ToggleShowPortrait", newValue);
    },
  },
  created() {
    window.document.title =
      "Overwatch Random Hero Picker | For teams and solo players";
    getSelectedLSHeroes();
    this.selectedHero = randomHero();
    let showPortraitLS = localStorage.getItem("showPortrait");

    if (showPortraitLS !== null) {
      this.showPortrait = showPortraitLS === "true";
    } else {
      localStorage.setItem("showPortrait", this.showPortrait);
    }
  },
  methods: {
    randomHeroHandler() {
      this.randomHero();
      sendEvent("Hero", "GetRandom", this.selectedHero.name);
    },
    randomHero: function () {
      this.selectedHero = randomHero();
      this.heroCount += 1;
    },
    getHeroesByRole(role) {
      return getHeroesByRole(role);
    },
    selectByRole(role) {
      selectByRole(role);
      saveSelectedHeroesToLS();
      sendEvent("Filter", "SelectRole", role);
    },
    unselectByRole(role) {
      unselectByRole(role);
      saveSelectedHeroesToLS();
      sendEvent("Filter", "UnselectRole", role);
    },
  },
};
</script>

<style scoped>
.main-container {
  overflow-x: hidden;
  background-color: #2c3e50;
  color: white;
  display: flex;
  width: 99%;
  min-height: 85vh;
  margin-bottom: 5em;
}

.left-content {
  display: flex;
  flex-direction: column;
  padding: 0 3% 0 3%;
}

.left-title,
.right-title {
  color: white;
  text-decoration: underline;
}

.left-content .chosen-hero-image {
  max-width: 75%;
  margin-left: auto;
  margin-right: auto;
}

.chosen-hero-name {
  margin: 1rem 1rem;
}

.random-hero-button,
.random-hero-button:hover,
.random-hero-button:focus,
.random-hero-button:active {
  font-size: 1.5rem;
  color: white;
  background-color: orangered;
  border-color: orangered;
}

.right-content {
  display: block;
  text-align: start;
}

.selected-heroes-info {
  font-size: 1.5rem;
  color: orange;
  margin: 1rem 0 0 0;
  font-weight: bold;
}

.selected-heroes-text {
  margin: 0;
  font-color: orange;
}

/** Large breakpoint or smaller */
@media (max-width: 991.98px) {
  .right-content {
    text-align: center;
  }

  .right-title {
    margin-top: 5%;
  }
}

.filter-description {
  display: block;
  font-family: Arial, Helvetica, sans-serif;
  font-size: 1rem;
  user-select: text;
  margin: 0;
  font-weight: bold;
}

/** Filter header */
.role-icon {
  max-height: 2em;
}

.role-header {
  margin: 0.5em 0.5em 0.5em 0;
}

.filter-header {
  display: flex;
  flex-direction: row;
  align-items: center;
}

/** Select / Unselect all buttons */
.all-button {
  color: white;
  border: none;
  font-size: 1.25rem;
  background-color: #0192c7;
  outline: none;
  padding: 0 0.3em;
  margin: 0 0.1em;
  height: min-content;
  transform: skewX(-10deg);
}

.all-button:active {
  transform: skewX(-10deg) translate(1px, 1px);
}

.select-all-button {
  background-color: rgb(51, 150, 31);
}

.unselect-all-button {
  background-color: rgb(231, 117, 9);
}

.all-button:hover {
  cursor: pointer;
}

.random-hero-button,
.random-hero-button:hover,
.random-hero-button:active,
.random-hero-button:focus,
.random-hero-button:enabled {
  border-radius: 0.25rem;
  padding: 0.25rem;
  font-size: 1.75rem;
  -webkit-appearance: none;
}

.hero-name-transition-enter-active {
  transition: all 0.1s ease-out;
}

.hero-name-transition-leave-active {
  transition: all 0.1s ease-in;
}

.hero-name-transition-enter,
.hero-name-transition-leave-to {
  transform: scaleY(0) translateZ(0);
  opacity: 0;
}

.hero-name-transition-enter-to {
  transform: scaleY(1) translateZ(0);
  opacity: 1;
}

.show-portrait-label {
  margin: 0 0 0 1%;
}

.card-group {
  display: flex;
  justify-content: flex-start;
  flex-wrap: wrap;
}
</style>
