// src/components/Navbar.vue
<template>
  <b-navbar toggleable="lg" type="dark" variant="dark">
    <b-navbar-toggle target="nav-collapse"></b-navbar-toggle>

    <b-collapse id="nav-collapse" is-nav>
      <b-navbar-brand href="https://owheropicker.com">
        <img class="ow-logo img-fluid" src="assets/imgs/navbar/ow-logo.svg" />
        <span class="title-text">Overwatch Hero Picker</span>
      </b-navbar-brand>
      <!-- Right aligned nav items -->
      <b-navbar-nav class="ml-auto">
        <b-nav-item to="/about">About</b-nav-item>
        <b-nav-item
          href="https://github.com/andrerfcsantos/overwatch-hero-picker"
          target="_blank"
        >
          Github
        </b-nav-item>
        <b-nav-item href="https://discord.gg/rwQMrCa" target="_blank">
          <img class="bmc-logo img-fluid" src="assets/imgs/discord.png" />
        </b-nav-item>
        <b-nav-item
          href="https://www.buymeacoffee.com/heropickers"
          target="_blank"
        >
          <img class="bmc-logo img-fluid" src="assets/imgs/navbar/bmc.svg" />
        </b-nav-item>
      </b-navbar-nav>
    </b-collapse>
  </b-navbar>
</template>

<script>
export default {
  name: "Navbar",
};
</script>

<style scoped>
a,
a:active,
a:focus,
a:hover,
a:visited,
a:visited:hover {
  text-decoration: none !important;
  color: white;
}

b-navbar {
  min-height: 5vh;
}

.title-text {
  font-size: 1.5rem;
  text-decoration: none;
}

li {
  font-size: 1.25em;
}

img {
  max-height: 2em;
}

img.bmc-logo {
  height: 1.5em;
  max-height: initial;
}

.ow-logo {
  padding-right: 0.5em;
}

.separator {
  color: grey;
}
</style>

// src/components/Navbar.tsx
"use client";

import { useState } from "react";
import Link from "next/link";

export default function Navbar() {
  const [isOpen, setIsOpen] = useState(false);

  return (
    <nav className="bg-[#343a40] min-h-[5vh] flex flex-wrap items-center justify-between px-4 py-2 lg:px-6">
      <button
        className="lg:hidden text-white text-2xl border border-gray-500 rounded px-2 py-1"
        onClick={() => setIsOpen(!isOpen)}
        aria-label="Toggle navigation"
      >
        &#9776;
      </button>

      <div
        className={`${isOpen ? "flex" : "hidden"} lg:flex flex-col lg:flex-row w-full lg:w-auto items-start lg:items-center justify-between flex-1`}
      >
        <a
          href="https://owheropicker.com"
          className="flex items-center no-underline text-white"
        >
          <img
            className="max-h-[2em] pr-2"
            src="/assets/imgs/navbar/ow-logo.svg"
            alt="Overwatch logo"
          />
          <span className="text-[1.5rem] text-white">Overwatch Hero Picker</span>
        </a>

        <div className="flex flex-col lg:flex-row lg:items-center gap-2 lg:gap-4 mt-2 lg:mt-0 text-[1.25em]">
          <Link href="/about" className="nav-link">
            About
          </Link>
          <a
            href="https://github.com/andrerfcsantos/overwatch-hero-picker"
            target="_blank"
            rel="noopener noreferrer"
            className="nav-link"
          >
            Github
          </a>
          <a
            href="https://discord.gg/rwQMrCa"
            target="_blank"
            rel="noopener noreferrer"
            className="nav-link"
          >
            <img
              className="h-[1.5em]"
              src="/assets/imgs/discord.png"
              alt="Discord"
            />
          </a>
          <a
            href="https://www.buymeacoffee.com/heropickers"
            target="_blank"
            rel="noopener noreferrer"
            className="nav-link"
          >
            <img
              className="h-[1.5em]"
              src="/assets/imgs/navbar/bmc.svg"
              alt="Buy Me a Coffee"
            />
          </a>
        </div>
      </div>
    </nav>
  );
}
